name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "*.ts"
      - "*.json"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      # Set up the repository
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Prepare Bun cache
        run: mkdir -p ~/.bun/install/cache

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: bun ci

      - name: Type check
        run: bun typecheck

      - name: Run Biome
        run: bun biome ci . --error-on-warnings

      - name: Run Test
        run: TESTRUNNER_RPC=${{ secrets.TESTRUNNER_RPC }} bun test
